language: node_js
node_js:
- 10
- 8
script: npm run test:coverage
addons:
  code_climate:
    repo_token:
      secure: "QLScNNrxpLZ4phuVz08j/bUjxAt+VVL1ywT690lB3bpKtdfB978UUhKNlc5gvekCqzcqM4AxwjNZQmP6l/KAMTAJZ43H8WQcLGXs2fI4XPnqjRx4ij67g2DIZIrvUVP2okgs8PJwNIpuWeIfL/rJdtqNe4J0/MpZGHMCLRJrgTsc/86uAxkFYA7BK1xc0toAHZglgwwU6mWZz8VjCDUWn4aK+UNdvrEAH4QbKKMOVNwj9gJmhwUPkwiZk5DiQ+SOpGx0jTaUU9mQ8BF5d0ZHffIEhUgn1vJwxxe1QlR5j9RJbrshaBAa5Be+k4GB9AmmaQu/b5G1y+HufnPPeeGHK/AGz+HcePepu0wgBPEXBrclO6kr7Ls/LO3s5x2IywZfFh6G3edix8ziuyPVAr7GSE+6yr8LKyluJO2fT8bvovzv9Ran5yO4KMZUzQJ1YUZ4UmfQcQ2INhQlKQJoT1j4K40uBV9LyL4nKriBLLWoTUvby2X89TXOiyDFrozCS4JmvClfaGHuePkBH3vLh4lN1pR47K585JpzUmYcgK0TQejnXGSboFh4TWxprsxKwB3vZstl3ziXUh+5GSaw6ytK/3aU91WWfrEA6m3/zZ08gnty9kEpvWvdCXc5lBrRpYqL2XmlgCaiozLLG7J9+D3hJb4iL/5ke5Unye9ZvdRc21M="
before_script:
- npm install codeclimate-test-reporter -g
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
notifications:
  email:
    recipients:
    - pritishvaidya94@gmail.com
    on_success: never
    on_failure: always
