language: node_js
node_js:
- 10
- 8
script: npm run test:coverage
addons:
  code_climate:
    repo_token:
      secure: "E8Z7pjd++l3N9loztkD1W1JFamddKDYb4ycNmejwSJf83Pr7y366JmE2raJnkZrQCYaR5BhOa1Moxh1igD9VYRlNurlEbW56JCV6jRMddoDNdl0OGgmNz9IyiVgX/OenbJr83HKJ9+hlDvxRvFe68jHEAn4VAe9z4GXbxekgoACaeVbrzg4dRBrAh8vJlrAVUuy2fQREwxYZnCCTsbj3xG9IcdJuqb10UorTowpNAILgfVa5uTcFYJ8BMBiSybWvrOfJv1EZoIh1x0aIUKNJuc8PLRAR8yL8Xi7R8SPKWXWivRnIc7YOzmauLFQUzFLz38RhHw6Nw80Sjf5i6lYxAit8LN7MtSIrLXlK/8K6kP5eXXZi+U7z+NNUX/LOrsnCSBQVHrBMzCNeIzLmz65yHmQx2FKtGSf/3l9dvFYDtTTWoBN7Ac8qNS5uppxJInC8lFInLo/GddZg49bnssD+8NGccr+dotZzo41Ruap61mYgeXdYh1twZqeNZT9XV0BRxNVP18hPnlBK/0sB5PvdkbcPD3iCl6HqgiFZ5bcZ4zWc5dwOF7r+HNjIssBKpLLbcPm/dcXH8s30gEabAdNDhV4aj8q0M9niMl65qGzzqZxvh0T/cEVzRBFWy1l4hPTw/QfGnC4hRFVRKP9zfMX6YhDvgnQSmvMvbIRPdOX1zMc="
before_script:
- npm install codeclimate-test-reporter -g
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
notifications:
  email:
    recipients:
    - pritishvaidya94@gmail.com
    on_success: never
    on_failure: always
